### ISSUE TITLE
怎么配置前后端分离的登录页

### ISSUE THREAD

**Issue by MrShao233** [xialugui/implementing-domain-driven-design#1]
你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题

**Comment by MrShao233** [comment]
https://github.com/spring-projects/spring-authorization-server/issues/474
这个是原来得问题

**Comment by xialugui** [comment]
> [spring-projects/spring-authorization-server#474](https://github.com/spring-projects/spring-authorization-server/issues/474) 这个是原来得问题

> 你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题

流程中断是因为cookie不一致导致的，框架默认使用 cookie来判断认证流程

**Comment by xialugui** [comment]
> 你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题

这个问题我没来得及修复，我的临时解决办法是只把登陆页面放在后端，其他页面可以分离。

**Comment by MrShao233** [comment]
> > [spring-project/spring-authorization-server#474](https://github.com/spring-projects/spring-authorization-server/issues/474)这个是原来得问题
> 
> > 你好，但是我在spring-authorization-server里看到的回答，我试了下你可以跳转到自定义登录页面，登录后后面的生成codetoken的流程也断了，我该怎么办解决这个问题
> 
> 处理流程是针对cookies的确认，通知使用cookie来确认确认


> > 你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题
> 
> 这个问题我没来得及修复，我的临时解决办法是只把登陆页面放在后端，其他页面可以分离。

那请问老哥现在有修复方案吗

**Comment by MrShao233** [comment]
我还有一个问题，就是关于配置数据库的，我怎么能把我现有的账号和这个框架结合起来

**Comment by xialugui** [comment]
> > > [spring-project/spring-authorization-server#474](https://github.com/spring-projects/spring-authorization-server/issues/474)这个是原来得问题
> > 
> > 
> > > 你好，但是我在spring-authorization-server里看到的回答，我试了下你可以跳转到自定义登录页面，登录后后面的生成codetoken的流程也断了，我该怎么办解决这个问题
> > 
> > 
> > 处理流程是针对cookies的确认，通知使用cookie来确认确认
> 
> > > 你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题
> > 
> > 
> > 这个问题我没来得及修复，我的临时解决办法是只把登陆页面放在后端，其他页面可以分离。
> 
> 那请问老哥现在有修复方案吗

目前有两个思路，1.cookie可能与前端有关(可能性不大)；2.改认证流程

**Comment by MrShao233** [comment]
> > > > [spring-project/spring-authorization-server#474](https://github.com/spring-projects/spring-authorization-server/issues/474)这个是原来得问题
> > > 
> > > 
> > > > 你好，但是我在spring-authorization-server里看到的回答，我试了下你可以跳转到自定义登录页面，登录后后面的生成codetoken的流程也断了，我该怎么办解决这个问题
> > > 
> > > 
> > > 处理流程是针对cookies的确认，通知使用cookie来确认确认
> > 
> > 
> > > > 你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题
> > > 
> > > 
> > > 这个问题我没来得及修复，我的临时解决办法是只把登陆页面放在后端，其他页面可以分离。
> > 
> > 
> > 那请问老哥现在有修复方案吗
> 
> 目前有两个思路，1.cookie可能与前端有关(可能性不大)；2.改认证流程

老哥，能加个微信聊吗，我微信19957411796

**Comment by xialugui** [comment]
> 

实现UserDetailsService接口

**Comment by xialugui** [comment]
> 我还有一个问题，就是关于配置数据库的，我怎么能把我现有的账号和这个框架结合起来

实现UserDetailsService接口

**Comment by xialugui** [comment]
> > > > > [spring-project/spring-authorization-server#474](https://github.com/spring-projects/spring-authorization-server/issues/474)这个是原来得问题
> > > > 
> > > > 
> > > > > 你好，但是我在spring-authorization-server里看到的回答，我试了下你可以跳转到自定义登录页面，登录后后面的生成codetoken的流程也断了，我该怎么办解决这个问题
> > > > 
> > > > 
> > > > 处理流程是针对cookies的确认，通知使用cookie来确认确认
> > > 
> > > 
> > > > > 你好，我在spring-authorization-server里看到你的回答，我试了下确实可以跳转到自定义登录页，但是登录后后面的生成code和token的流程也会断了，我该怎么解决这个问题
> > > > 
> > > > 
> > > > 这个问题我没来得及修复，我的临时解决办法是只把登陆页面放在后端，其他页面可以分离。
> > > 
> > > 
> > > 那请问老哥现在有修复方案吗
> > 
> > 
> > 目前有两个思路，1.cookie可能与前端有关(可能性不大)；2.改认证流程
> 
> 老哥，能加个微信聊吗，我微信19957411796

微信号： xialugui

**Comment by hezhongfeng** [comment]
这个问题我解决了，在进行授权跳转的时候，Server端会记住这个授权链接，所以默认的登录页面才可以在登录成功后继续完成授权。

我的做法是，在前端（SPA）项目访问Server的接口，查询是否存在这个RedirectUrl，如果存在就证明是授权需要跳转，否则就是普通登录。

```
  @GetMapping("/content")
  public RespResult<String> getCurrentContent(HttpServletRequest request,
      HttpServletResponse response) {

    SavedRequest savedRequest = new HttpSessionRequestCache().getRequest(request, response);

    String redirectUrl = "";

    // 这里可能为空，需要判断
    if (savedRequest != null) {
      redirectUrl = savedRequest.getRedirectUrl();
    }
    return new RespResult<String>(200, "", redirectUrl);
  }
```

**Comment by xialugui** [comment]
@hezhongfeng 有空我验证一下。

**Comment by hezhongfeng** [comment]
然后在收到code的时候，我想用前端去接，然后拿着这个code通过rest接口获取accessToken
但是这步没搞好

**Comment by xialugui** [comment]
> 然后在收到code的时候，我想用前端去接，然后拿着这个code通过rest接口获取accessToken 但是这步没搞好
@hezhongfeng auth2的很多小问题都是由参数不正确引起的。你的这个问题不看源码很难排查。

**Comment by hezhongfeng** [comment]
我其实可以自己去写使用code获取token的过程，只不过想着用现成的~找找源码吧

**Comment by xialugui** [comment]
@hezhongfeng 👍
